name: payeewise
description: Manage Your Budget Wisely with Payeewise.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #utils
  path_provider: ^2.0.15
  get_it: ^7.6.0

  #framework
  auto_route: ^7.7.0
  flex_color_scheme: ^7.1.2
  equatable: ^2.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  
  #storage
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0+1
  assets_gen: any
  auto_route_generator: any       
  build_runner:                    

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  #
  
  
